#!/usr/local/bin/ruby -Ku
# -*- coding: utf-8 -*-
require File.expand_path(File.join(File.dirname(__FILE__), "talk_client"))
object = Chat::TalkClient.new
object.talk(ARGV.to_s, :tone => 100, :program_no => 1, :speed => 100, :volume => 80)
